2019-04-12,20:27:07: W E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\util\deprecation.py:323] From E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-12,20:27:26: W E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\util\deprecation.py:323] From E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-04-12,20:27:45: I E:/WorkSpace/tea_weeds_server/tea_weeds_server.py:39] tea_weeds_server start success...
2019-04-12,22:22:59: E E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py:400] Exception calling application: cannot reshape array of size 1835894 into shape (2136,3216,3)
Traceback (most recent call last):
  File "E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py", line 392, in _call_behavior
    return behavior(argument, context), True
  File "E:/WorkSpace/tea_weeds_server/tea_weeds_server.py", line 26, in classifier
    request.image.channel)
ValueError: cannot reshape array of size 1835894 into shape (2136,3216,3)
2019-04-12,22:28:46: W E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\util\deprecation.py:323] From E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-12,22:28:58: W E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\util\deprecation.py:323] From E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-04-12,22:29:09: I E:/WorkSpace/tea_weeds_server/tea_weeds_server.py:39] tea_weeds_server start success...
2019-04-12,22:29:58: E E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py:400] Exception calling application: cannot reshape array of size 1835894 into shape (2136,3216,3)
Traceback (most recent call last):
  File "E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py", line 392, in _call_behavior
    return behavior(argument, context), True
  File "E:/WorkSpace/tea_weeds_server/tea_weeds_server.py", line 26, in classifier
    request.image.channel)
ValueError: cannot reshape array of size 1835894 into shape (2136,3216,3)
2019-04-12,22:38:04: E E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py:400] Exception calling application: cannot reshape array of size 1835894 into shape (2136,3216,3)
Traceback (most recent call last):
  File "E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py", line 392, in _call_behavior
    return behavior(argument, context), True
  File "E:/WorkSpace/tea_weeds_server/tea_weeds_server.py", line 26, in classifier
    request.image.channel)
ValueError: cannot reshape array of size 1835894 into shape (2136,3216,3)
2019-04-12,22:39:30: E E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py:400] Exception calling application: cannot reshape array of size 1835894 into shape (2136,3216,3)
Traceback (most recent call last):
  File "E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py", line 392, in _call_behavior
    return behavior(argument, context), True
  File "E:/WorkSpace/tea_weeds_server/tea_weeds_server.py", line 26, in classifier
    request.image.channel)
ValueError: cannot reshape array of size 1835894 into shape (2136,3216,3)
2019-04-12,23:22:48: E E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py:400] Exception calling application: cannot reshape array of size 2447860 into shape (2136,3216,3)
Traceback (most recent call last):
  File "E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py", line 392, in _call_behavior
    return behavior(argument, context), True
  File "E:/WorkSpace/tea_weeds_server/tea_weeds_server.py", line 26, in classifier
    request.image.channel)
ValueError: cannot reshape array of size 2447860 into shape (2136,3216,3)
2019-04-12,23:33:40: E E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py:400] Exception calling application: cannot reshape array of size 1836032 into shape (2136,3216,3)
Traceback (most recent call last):
  File "E:\WorkSpace\tea_weeds_server\venv\lib\site-packages\grpc\_server.py", line 392, in _call_behavior
    return behavior(argument, context), True
  File "E:/WorkSpace/tea_weeds_server/tea_weeds_server.py", line 26, in classifier
    request.image.channel)
ValueError: cannot reshape array of size 1836032 into shape (2136,3216,3)
